services:
  - type: web
    name: washing-machine
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.11.0

